import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import NavMenu from "@/components/layout/NavMenu";

export const metadata: Metadata = {
    title: "dZENcode",
    description: "Generated by Igor Sytnikov",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <div className="flex">
                    <NavMenu />
                    {children}
                </div>
            </body>
        </html>
    );
}
