import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
    title: "dZENcode",
    description: "Generated by Igor Sytnikov",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Header />
            <body>{children}</body>
        </html>
    );
}
